export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const MESSAGES_FETCHED = 'MESSAGES_FETCHED';
export const MESSAGE_CREATED = 'MESSAGE_CREATED';
export const MESSAGE_UPDATED = 'MESSAGE_UPDATED';
export const MESSAGE_DELETED = 'MESSAGE_DELETED';
export const CURRENT_MESSAGE = 'CURRENT_MESSAGE';